name = "My 1.21.1 Pack"
author = "you"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74c024f9c2bd0e30743008a28ce921e4f2416511fee18bc3e6fd84ba83db03ca"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
